### ISSUE TITLE
Benchmark the HPMC + pair potential systems

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/hoomd-benchmarks#30]
## Description

Benchmark systems that use the `hpmc.pair.user` classes.

## Proposed solution

At the least, we should add a system that uses the `hpmc.pair.user.CPPPotential` class. Some ideas of systems to add:

1. Hard disks/spheres with a short-range attraction
2. Polyhedra with square-well attractions on the faces
3. Point particles with a pair potential, e.g. LJ

## Developer

I will do this.

**Comment by joaander** [comment]
It would be great to have these benchmarks to check for performance regressions in HOOMD releases.
